requirements:
  sensors:
    - Os:
        dont_send: True

discovery:
  homeassistant: # Must match discovery preset name
    - topic: "brightness/get"
      disable: True
      payload:
        name: "Brightness level"
        unit_of_measurement: "%"
    - topic: "brightness/set"
      type: "light"
      payload:
        name: "Brightness"